import '@ephin-travel-kit/ui/styles.css';

import './globals.css';
import type { Metadata } from 'next';

import { Geist } from 'next/font/google';

import { Header } from '@/components/layout';

const geist = Geist({ subsets: ['latin'] });

export const metadata: Metadata = {
  description: 'Generated by create turbo',
  title: 'Create Turborepo',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={geist.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
